title:            
Description:      Saining Xie Personal Site
baseurl:          "http://vcl.ucsd.edu/~sxie"
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          "http://vcl.ucsd.edu/~sxie/about"
  - name:         Blog
    url:          "http://vcl.ucsd.edu/~sxie"
    #external:     true
  - name:         Email
    url:          mailto:s9xie@eng.ucsd.edu
    external:     true
  - name:         GitHub
    url:          http://github.com/s9xie
    external:     true
highlighter:	  pygments
permalink:        pretty
markdown:         kramdown
kramdown:	
    input: GFM
#redcarpet:
  #extensions: ["smart", "footnotes","fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"] 
